# POST https://fullstack-notes-app.fly.dev/api/users
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "josh",
    "name": "Superuser",
    "password": "salainen"
}
