PUT http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "I don’t understand",
    "date": "2022-10-13T03:23:08.793Z",
    "important": false,
    "id": "6347849c090dfd4713c5c87b"
  }